root = "."
testdata_dir = "testdata"
tmp_dir = "bin/tmp"

[build]
  args_bin = []
  bin = "./bin/tmp/qplayground"
  pre_cmd = []
  cmd = "go build -o ./bin/tmp/qplayground ./cmd/app/main.go"
  post_cmd = []
  delay = 1000
  exclude_dir = ["assets", "tmp", "node_modules", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go", ".min.css"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css"]
  include_file = ["public/hot"]
  kill_delay = "0s"
  log = "air.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
