package main

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Automation Report - {{AUTOMATION_NAME}}</title>
    <style>
        ` + cssStyles + `
    </style>
</head>
<body>
    <div class="container">
        <header class="report-header">
            <h1>🤖 Automation Report</h1>
            <div class="automation-info">
                <h2>{{AUTOMATION_NAME}}</h2>
                <p class="description">{{AUTOMATION_DESCRIPTION}}</p>
                <div class="meta-info">
                    <span class="timestamp">Generated: {{GENERATED_AT}}</span>
                    <span class="run-id">Run: {{TIMESTAMP}}</span>
                    <span class="status {{STATUS_CLASS}}">{{STATUS}}</span>
                </div>
            </div>
        </header>

        <div class="summary-section">
            <h3>📊 Executive Summary</h3>
            <div class="summary-grid">
                <div class="summary-card">
                    <div class="card-header">Execution Overview</div>
                    <div class="card-content">
                        <div class="metric">
                            <span class="metric-label">Total Runs:</span>
                            <span class="metric-value">{{TOTAL_RUNS}}</span>
                        </div>
                        <div class="metric">
                            <span class="metric-label">Successful:</span>
                            <span class="metric-value success">{{SUCCESSFUL_RUNS}}</span>
                        </div>
                        <div class="metric">
                            <span class="metric-label">Failed:</span>
                            <span class="metric-value error">{{FAILED_RUNS}}</span>
                        </div>
                        <div class="metric">
                            <span class="metric-label">Success Rate:</span>
                            <span class="metric-value">{{SUCCESS_RATE}}</span>
                        </div>
                    </div>
                </div>
                
                <div class="summary-card">
                    <div class="card-header">Structure</div>
                    <div class="card-content">
                        <div class="metric">
                            <span class="metric-label">Total Steps:</span>
                            <span class="metric-value">{{TOTAL_STEPS}}</span>
                        </div>
                        <div class="metric">
                            <span class="metric-label">Total Actions:</span>
                            <span class="metric-value">{{TOTAL_ACTIONS}}</span>
                        </div>
                        <div class="metric">
                            <span class="metric-label">Output Files:</span>
                            <span class="metric-value">{{OUTPUT_FILES_COUNT}}</span>
                        </div>
                    </div>
                </div>
                
                <div class="summary-card">
                    <div class="card-header">Performance</div>
                    <div class="card-content">
                        <div class="metric">
                            <span class="metric-label">Total Duration:</span>
                            <span class="metric-value">{{TOTAL_DURATION}}</span>
                        </div>
                        <div class="metric">
                            <span class="metric-label">Average Duration:</span>
                            <span class="metric-value">{{AVERAGE_DURATION}}</span>
                        </div>
                        <div class="metric">
                            <span class="metric-label">Execution Time:</span>
                            <span class="metric-value">{{EXECUTION_TIME}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {{ERROR_SECTION}}

        {{STEPS_SECTION}}

        {{ACTIONS_SECTION}}

        {{OUTPUT_FILES_SECTION}}

        <footer class="report-footer">
            <p>Report generated by QPlayground CLI on {{GENERATED_AT}}</p>
            <p>For more information, visit <a href="https://qplayground.com" target="_blank">qplayground.com</a></p>
        </footer>
    </div>
</body>
</html>`